apiVersion: apiextensions.crossplane.io/v1alpha1
data:
  bool: false
  complex:
    a: b
    c:
      d: e
  int: 123
  list:
  - a
  - b
  - c
  region: eu-central-1
  simple: value
  tags:
    common: set
    of: tags
    it: works
    hell: yeah
kind: EnvironmentConfig
metadata:
  name: example-environment
